#+TITLE: Tips for C++
* Tips for =C++=
** How to trim =std::stirng=
trim functions are copied from [[https://stackoverflow.com/questions/216823/whats-the-best-way-to-trim-stdstring][stackoverflow]].
#+begin_src c++
  #include <algorithm>
  #include <cctype>
  #include <locale>
  // trim from start (in place)
  static inline void ltrim(std::string &s) {
    s.erase(s.begin(), std::find_if(s.begin(), s.end(), [](unsigned char ch) {
      return !std::isspace(ch);
    }));
  }

  // trim from end (in place)
  static inline void rtrim(std::string &s) {
    s.erase(std::find_if(s.rbegin(), s.rend(), [](unsigned char ch) {
      return !std::isspace(ch);
    }).base(), s.end());
  }

  // trim from both ends (in place)
  static inline void trim(std::string &s) {
    ltrim(s);
    rtrim(s);
  }

  // trim from start (copying)
  static inline std::string ltrim_copy(std::string s) {
    ltrim(s);
    return s;
  }

  // trim from end (copying)
  static inline std::string rtrim_copy(std::string s) {
    rtrim(s);
    return s;
  }

  // trim from both ends (copying)
  static inline std::string trim_copy(std::string s) {
    trim(s);
    return s;
  }
#+end_src

** Better way to create an array with the variable size
   I refer to this [[https://stackoverflow.com/a/21377382][answer]] and this [[https://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique][link]]. An example is
   : std::unique_ptr<unsigned char[]> testData(new unsigned char[16000]());
   : auto testData = std::make_unique<unsigned char[]>(16000);
   Note that =make_unique= is available from =C++14=.

** It is preferred to use =make_unique=
   =make_unique= is exception safe:
   : foo(make_unique<T>(), make_unique<U>()); // exception safe
   : foo(unique_ptr<T>(new T()), unique_ptr<U>(new U())); // unsafe*
   In the second line, the unspecified-evaluation-order may trigger
   memory leak. I refer to [[https://stackoverflow.com/a/37514601][this answer]], [[https://stackoverflow.com/a/22571331][this answer]], and the
   [[https://isocpp.org/blog/2019/06/quick-q-differences-between-stdmake-unique-and-stdunique-ptr-with-new][blog]]. They own the credits.

** Do not abuse =std::endl=
   Use '\n' if you really want a new line. Please consult this [[https://kuhllib.com/2012/01/14/stop-excessive-use-of-stdendl/][post]].

** Replace a character in =std::stirng=
   I checked this [[https://stackoverflow.com/a/2896627][answer]]. It only works if you want replace a
   character with a character.

   An example to replace a character with a
   desired one:
   #+begin_src c++
     std::string s = "example string";
     std::replace( s.begin(), s.end(), 'x', 'y'); // replace all 'x' to 'y'
   #+end_src

   You may want to replace a sub-string with another sub-string like:
   #+begin_src c++
     std::string s = "pT1.0to2.0_yAbsMax2.4";
     for (auto pos = s.find(".0"); pos!=std::string::npos;
          pos = s.find(".0", pos)) { // find ".0" from pos (pos is position index)
       s.replace(pos, 2, ""); // replace following 2 character starting from pos
      }
   #+end_src

** Format the =std::string=
   In principle, you could make use of =std::sprintf= and =std::snprintf=
   before =C++20=. The =snprintf= starts from =C++11=. You would like to
   refer to [[https://en.cppreference.com/w/cpp/io/c/fprintf][the reference]].

   It is also helpful to warp them up. I copied the code from the
   [[https://stackoverflow.com/a/26221725][answer]]. It looks like:
   #+begin_src c++
     #include <memory>
     #include <string>
     #include <stdexcept>

     template<typename ... Args>
     std::string string_format( const std::string& format, Args ... args )
     {
         int size_s = std::snprintf( nullptr, 0, format.c_str(), args ... ) + 1; // Extra space for '\0'
         if( size_s <= 0 ){ throw std::runtime_error( "Error during formatting." ); }
         auto size = static_cast<size_t>( size_s );
         auto buf = std::make_unique<char[]>( size );
         std::snprintf( buf.get(), size, format.c_str(), args ... );
         return std::string( buf.get(), buf.get() + size - 1 ); // We don't want the '\0' inside
     }
   #+end_src
   It make use of the variadic template in the declaration (see
   [[*Parameter pack and variadic template][Parameter pack and variadic template]]). And it make use of a
   variable size of array instead of fixed size arrays. This is
   because =snprintf= have the following properties:
   #+begin_quote
   If the resulting string gets truncated due to buf_size limit,
   function returns the total number of characters (not including the
   terminating null-byte) which would have been written, if the limit
   was not imposed.
   #+end_quote

   A =C++20= solution is [[https://en.cppreference.com/w/cpp/utility/format/format][=std::format=]].

** Parameter pack and variadic template
   You could refer to the [[https://stackoverflow.com/a/19923558][answer]] and the [[https://en.cppreference.com/w/cpp/language/parameter_pack][link]]. I do not understand the
   details very much. An example is in [[*Format the =std::string=][Format the =std::string=]].
