#+TITLE: Perl tips
* One-line phraser
** =grep= and =sed= print
   Try =perl -ne 'print if /pattern/' input.txt=. For find in
   a range and print, try
   =perl -ne 'print if (m/PatternA/..m/PatternB/)'=.
** =sed= replacement
   To replace the original string with the new in a specific range,
   try =perl -ne 's/this/that/g if (m/PatternA/..m/PatternB/)'=.
   I never try other cases without specificing a range.

* General scripts
** String substitution                                                          :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-16 Tue 14:29]

 Please use
 : my $newstring = $oldstring =~ s/foo/bar/r;
 ~/r~ option is necessary to keep the original one. See [[https://stackoverflow.com/questions/3440363/perl-use-s-replace-and-return-new-string][answer]] and
 [[https://stackoverflow.com/questions/22836/how-do-i-perform-a-perl-substitution-on-a-string-while-keeping-the-original][answer]].
** Redirect output from system commands in perl                                 :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-16 Tue 14:35]

 Plain ~>~ only catch ~STDOUT~. Redirect ~STDERR~ to ~STDOUT~ needs ~2>&1~.
 An example
 : system("ls -lst > example.txt 2>&1");
 This is a dangerous way. Safer ways are discussed in [[https://stackoverflow.com/questions/7799045/best-way-to-capture-output-from-system-command-to-a-text-file][answer]]
 More info in [[https://stackoverflow.com/questions/818255/in-the-shell-what-does-21-mean][answer]],
** Run system comands                                                           :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-16 Tue 15:49]

 Make use of ~system~ command. See the [[https://perldoc.perl.org/functions/system][link]].
** Return a value in subroutine                                                 :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-16 Tue 15:55]

 Make use of ~return~ at the end of the subroutine. See the [[https://www.perltutorial.org/perl-subroutine/][link]] and
 [[https://www.learn-perl.org/en/Subroutines][link]].
** How to call subroutine in command line                                       :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-17 Wed 09:51]

 I checked this [[https://stackoverflow.com/questions/23039028/calling-perl-subroutines-from-the-command-line][link]]. I choose the way using hash. You may want to
 check others.

 I quote the method here. The script is
 #+BEGIN_src perl
 #!/usr/bin/perl

 use strict;
 use warnings;
 use 5.010;

 sub fields {
   say 'this is fields';
 }

 sub another {
   say 'this is another subroutine';
 }

 my %functions = (
   fields  => \&fields,
   another => \&another,
 );

 my $function = shift;

 if (exists n$functions{$function}) {
   $functions{$function}->();
 } else {
   die "There is no function called $function available\n";
 }
 #+END_src

 The usage is
 #+begin_example
 $ ./dispatch_tab fields
 this is fields
 $ ./dispatch_tab another
 this is another subroutine
 $ ./dispatch_tab xxx
 There is no function called xxx available
 #+end_example
** How to check if a file is plain file                                         :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-17 Wed 23:33]

 ~-f~ function is useful to check if a file is a plain file. See the
 [[https://stackoverflow.com/questions/206320/how-do-i-distinguish-a-file-from-a-directory-in-perl][answer]] and [[https://perldoc.perl.org/perlfunc#-X-FILEHANDLE][link]]. A usage can be checked in the doc for [[https://perldoc.perl.org/functions/readdir][readdir]].
 #+begin_src perl
   opendir(my $dh, $some_dir) || die "Can't opendir $some_dir: $!";
   my @dots = grep { /^\./ && -f "$some_dir/$_" } readdir($dh);
   closedir $dh;
 #+end_src
** Push, pop, shift, unshift arrays                                             :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 00:23]

 See the [[https://www.learn-perl.org/en/Arrays][link]].
 - ~push(@array, element)~, add element or elements into the end of the
   array
 - ~$popped = pop(@array)~, delete and return the last element of the
   array
 - ~$shifted = shift(@array)~, delete and return the first element of the
   array
 - ~unshift(@array)~, add element or elements into the beginning of the
   array
** Break loop                                                                   :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 01:09]

 You could use ~last~ statement to break the innermost loop. Other usage
 can be found in the [[https://perldoc.perl.org/functions/last][link]]. And here is a related [[https://stackoverflow.com/questions/303216/how-do-i-break-out-of-a-loop-in-perl][question]] on
 ~Stackoverflow~.
** Pass arguments to subroutine                                                 :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 01:21]

 See this [[https://www.perltutorial.org/passing-parameters-to-subroutine/][link]]. The first argument is ~$_[0]~ and the second is
 ~$_[1]~. The array need to be passed as reference. See this [[https://stackoverflow.com/questions/10729015/pass-array-and-scalar-to-a-perl-subroutine][question
 and answer]].
** system                                                                       :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 16:19]

 Please check the [[https://perldoc.perl.org/functions/system][link]].
** Replace string                                                               :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 16:27]

 We need the operator [[https://perldoc.pl/perlfunc#s///][s]].
 An example:
 #+begin_src perl
   my $myvar = "abc";
   print ("$myvar\n");
   $myvar =~ s/a/A/; # this will modify the original string
   print( $myvar =~ s/b/B/ ); # $myvar won't be printed.
   print( $myvar =~ s/c/C/r ); # r option guarantee original one unchanged
   $mynewvar = $myvar =~ s/c/C/r; # a new string saved in $mynewvar
 #+end_src
 Please note the difference between the return value with and without
 option ~r~. Also see this [[https://stackoverflow.com/questions/3440363/perl-use-s-replace-and-return-new-string][answer]].
** Ignore case sensitivity                                                      :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 16:52]

 You can use ~i~ mdifier, an example ~/G[a-b].*/i~. Check this [[https://stackoverflow.com/questions/9655164/regex-ignore-case-sensitivity][answer]].
** Boolean in perl                                                              :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 16:54]

 I quote the [[https://stackoverflow.com/questions/1036347/how-do-i-use-boolean-variables-in-perl][answer]] here.
 The following are false and others are true.
 #+begin_example
 0
 '0'
 undef
 ''  # Empty scalar
 ()  # Empty list
 ('')
 #+end_example
** Sort an array                                                                :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 17:08]

 Make use of [[https://perldoc.perl.org/functions/sort][sort]].
** Open a file                                                                  :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 17:09]

 Make use of [[https://perldoc.perl.org/functions/open][open]]. It needs file handle, mode, and filename.
 : open(filehandle,mode,filename)
 You have three modes:
 | mode   | operand |
 |--------+---------|
 | read   | ~<~       |
 | write  | ~>~       |
 | append | ~>>~      |
 Also check this [[https://www.perltutorial.org/perl-open-file/][link]].
** Read files                                                                   :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 17:12]

 Check this [[https://www.perltutorial.org/perl-read-file/][link]].
** Read multi-line                                                              :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 21:03]

 You need to redefine the variable ~$/~ to ~undef~, which is dangerous.
 Then ~<>~ will read the file in one chunk. See the [[https://stackoverflow.com/questions/1030787/multiline-search-replace-with-perl][discussions]].
** undef                                                                        :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 21:06]

 See this [[https://perldoc.perl.org/functions/undef][link]].
** Replace characters in multiple lines                                         :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 21:07]

 Use the modifier ~/s~. Check this [[https://stackoverflow.com/questions/6764350/extract-text-from-a-multiline-string-using-perl][link]].
** Check if a variable is defined                                               :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 21:08]

 You can make use of [[https://perldoc.perl.org/functions/defined][defined]].
** Read a directory                                                             :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-18 Thu 21:11]

 Make use of ~opendir~ and ~readdir~. See this [[https://perldoc.perl.org/functions/readdir][link]].

** how to select lines without containing a pattern                             :NOTE:
   :PROPERTIES:
   :GROUP:    perl
   :END:
 [2021-11-25 Thu 16:45]

 Please check this [[https://stackoverflow.com/questions/406230/regular-expression-to-match-a-line-that-doesnt-contain-a-word][answer]], using =(?!)=.
